name: bouncy_widget
description: A simple bouncing widget.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
